name: Build and Test Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Frontend and Backend
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Backend Dependencies
        run: npm install --prefix ./packages/backend

      - name: Build Backend
        run: npm run build --prefix ./packages/backend

      - name: Install Frontend Dependencies
        run: npm install --prefix ./packages/frontend

      - name: Build Frontend
        run: npm run build --prefix ./packages/frontend
